apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app-ruby.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "voting-app-ruby.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voting-app-ruby.name" . }}
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voting-app-ruby.name" . }}
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.db }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
