apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-vote
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.votePort }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: vote
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-result
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.resultPort }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: result
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app-ruby.fullname" . }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "voting-app-ruby.name" . }}
    app.kubernetes.io/component: db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app-ruby.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "voting-app-ruby.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "voting-app-ruby.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
